/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor/route'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as EditorWorkflowIdImport } from './routes/editor/$workflowId'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as DashboardWorkflowsIndexImport } from './routes/dashboard/workflows/index'

// Create/Update Routes

const EditorRouteRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const EditorWorkflowIdRoute = EditorWorkflowIdImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => EditorRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

const DashboardWorkflowsIndexRoute = DashboardWorkflowsIndexImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/editor/$workflowId': {
      id: '/editor/$workflowId'
      path: '/$workflowId'
      fullPath: '/editor/$workflowId'
      preLoaderRoute: typeof EditorWorkflowIdImport
      parentRoute: typeof EditorRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/dashboard/workflows/': {
      id: '/dashboard/workflows/'
      path: '/workflows'
      fullPath: '/dashboard/workflows'
      preLoaderRoute: typeof DashboardWorkflowsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardWorkflowsIndexRoute: typeof DashboardWorkflowsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardWorkflowsIndexRoute: DashboardWorkflowsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface EditorRouteRouteChildren {
  EditorWorkflowIdRoute: typeof EditorWorkflowIdRoute
}

const EditorRouteRouteChildren: EditorRouteRouteChildren = {
  EditorWorkflowIdRoute: EditorWorkflowIdRoute,
}

const EditorRouteRouteWithChildren = EditorRouteRoute._addFileChildren(
  EditorRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/editor': typeof EditorRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/editor/$workflowId': typeof EditorWorkflowIdRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/workflows': typeof DashboardWorkflowsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/editor': typeof EditorRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/editor/$workflowId': typeof EditorWorkflowIdRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/workflows': typeof DashboardWorkflowsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/editor': typeof EditorRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/editor/$workflowId': typeof EditorWorkflowIdRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/editor'
    | '/auth/login'
    | '/editor/$workflowId'
    | '/auth/'
    | '/dashboard/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/editor'
    | '/auth/login'
    | '/editor/$workflowId'
    | '/auth'
    | '/dashboard/workflows'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/editor'
    | '/auth/login'
    | '/editor/$workflowId'
    | '/auth/'
    | '/dashboard/workflows/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  EditorRouteRoute: typeof EditorRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  EditorRouteRoute: EditorRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard",
        "/editor"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/login",
        "/auth/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/workflows/"
      ]
    },
    "/editor": {
      "filePath": "editor/route.tsx",
      "children": [
        "/editor/$workflowId"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/editor/$workflowId": {
      "filePath": "editor/$workflowId.tsx",
      "parent": "/editor"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/dashboard/workflows/": {
      "filePath": "dashboard/workflows/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
